"""
Interactive Duplicate Image Review and Cleanup

This module reads a CSV file generated by the duplicate image evaluation script,
which contains pairs of visually similar images (potential duplicates).

For each detected duplicate, it presents a GUI window showing the original and duplicate images side by side.

The user can:
- Press DEL to remove the duplicate (smaller) image.
- Press ENTER to keep both images and move to the next pair.

The script tracks which files were removed, records the size of each removed file in kilobytes, and saves the updated
DataFrame to a new CSV file with a '_processed' suffix. At the end, it prints the total space saved in kilobytes
to the console.
"""

import os
import pandas as pd
from PIL import Image, ImageTk
import tkinter as tk

# Configuration
INPUT_CSV_FOLDER_PATH = "report"
INPUT_CSV_FILE_NAME = "duplicate_image_report.csv"
OUTPUT_CSV_FOLDER_PATH = "report"
OUTPUT_CSV_FILE_NAME = "duplicate_image_report_processed.csv"

# Read the CSV
input_csv_path = os.path.join(INPUT_CSV_FOLDER_PATH, INPUT_CSV_FILE_NAME)
if not os.path.exists(input_csv_path):
    raise FileNotFoundError(f"Input CSV not found: {input_csv_path}")
df = pd.read_csv(input_csv_path, sep='@', dtype=str)
if 'removed' not in df.columns:
    df['removed'] = ''

# Add a new column for removed file size in kilobytes
if 'removed_kb' not in df.columns:
    df['removed_kb'] = ''

# Find all pairs (big, small) where dupe_type is 'dupe_small' and dupe_of is not empty
pairs = df[df['dupe_type'] == 'dupe_small' ].copy()

def show_images_side_by_side(img1_path, img2_path, window_title):
    window = tk.Tk()
    window.title(window_title)
    # Ensure the window is focused and on top
    window.lift()
    window.attributes('-topmost', True)
    window.focus_force()
    window.after(100, lambda: window.attributes('-topmost', False))
    # Load images and resize for display
    def load_and_resize(path, maxsize=(600, 600)):
        img = Image.open(path)
        img.thumbnail(maxsize, Image.Resampling.LANCZOS)
        return ImageTk.PhotoImage(img)
    img1 = load_and_resize(img1_path)
    img2 = load_and_resize(img2_path)
    # Layout
    panel1 = tk.Label(window, image=img1)
    panel1.pack(side="left", padx=10, pady=10)
    panel2 = tk.Label(window, image=img2)
    panel2.pack(side="right", padx=10, pady=10)
    # Instructions
    instr = tk.Label(window, text="DEL = remove duplicate (right), ENTER = keep both")
    instr.pack(side="bottom", pady=10)
    # Key event handling
    result = {'removed': None}
    def on_del(event):
        result['removed'] = 1
        window.destroy()
    def on_enter(event):
        result['removed'] = 0
        window.destroy()
    window.bind('<Delete>', on_del)
    window.bind('<Return>', on_enter)
    window.mainloop()
    return result['removed']

# Track total bytes removed
removed_bytes = 0
# Iterate through all dupe pairs
for idx, row in pairs.iterrows():
    small_path = row['file']
    big_path = row['dupe_of']
    if not (os.path.exists(small_path) and os.path.exists(big_path)):
        df.at[idx, 'removed'] = 'file_missing'
        continue
    window_title = f"Duplicate Review: {os.path.basename(small_path)}"
    removed = show_images_side_by_side(big_path, small_path, window_title)
    df.at[idx, 'removed'] = removed
    # If removed, delete the small file and record its size
    if removed == 1:
        try:
            file_size = os.path.getsize(small_path)
            removed_bytes += file_size
            os.remove(small_path)
            df.at[idx, 'removed_kb'] = round(file_size / 1024, 2)
        except Exception as e:
            print(f"Failed to remove {small_path}: {e}")
            df.at[idx, 'removed_kb'] = ''
    else:
        df.at[idx, 'removed_kb'] = ''

# Save the updated DataFrame
os.makedirs(OUTPUT_CSV_FOLDER_PATH, exist_ok=True)
output_csv_path = os.path.join(OUTPUT_CSV_FOLDER_PATH, OUTPUT_CSV_FILE_NAME)
df.to_csv(output_csv_path, sep='@', index=False)
print(f"Done. Results written to {output_csv_path}")
# Print total space saved in kilobytes
print(f"Total space saved: {round(removed_bytes / 1024, 2)} KB")
